
version: '3.8'

services:
  web:
    image: sunghyun1356/ceos
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ceos-db.catymkthpwcp.ap-northeast-2.rds.amazonaws.com/ceos
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Ab1356!!g

  nginx:
    container_name: nginx
    image: sunghyun1356/ceos_nginx
    ports:
      - 81:80
    depends_on:
      - web

volumes:
  db_data:

networks:
  ceos:
    driver: bridge
