name: Deploy Development Server

## 워크플로가 트리거되는 이벤트 설정
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

## 권한 설정
permissions:
  contents: read

## 작업 설정
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      ## 코드를 체크아웃합니다.
      - name: Checkout
        uses: actions/checkout@v4

      ## JDK 17을 설치합니다.
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      ## Gradle 실행 권한 부여
      - name: Give permission
        run: chmod +x ./gradlew

      ## Gradle로 프로젝트를 빌드합니다.
      - name: Build with Gradle
        run: ./gradlew bootJar

      ## 웹 이미지를 Docker로 빌드하고 Docker Hub에 푸시합니다.
      - name: Web Docker build and push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t sunghyun1356/ceos .
          docker push sunghyun1356/ceos
          docker build -f dockerfile-nginx -t sunghyun1356/ceos_nginx .
          docker push sunghyun1356/ceos_nginx

      ## 개인 키를 사용하여 원격 SSH 명령 실행
      - name: Executing remote SSH commands using private key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            ## Docker 및 Docker Compose 설치
            sudo apt-get update
            sudo apt-get remove -y containerd
            sudo apt-get install -y docker.io docker-compose

            ## 원하는 디렉토리로 이동
            cd /home/ubuntu/
            
            ## .env 파일 생성
            echo "${{ secrets.ENV_VARS }}" | sudo tee .env > /dev/null
            
            ## docker-compose.yaml 파일 생성
            echo "${{ secrets.DOCKER_COMPOSE }}" | sudo tee docker-compose.yaml > /dev/null
            
            ## docker-compose 실행
            sudo chmod 666 /var/run/docker.sock
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker pull sunghyun1356/ceos
            sudo docker pull sunghyun1356/ceos_nginx
            sudo docker-compose -f docker-compose.yaml --env-file ./.env up -d
            sudo docker image prune -f
